image: node:16.4.2

variables:
  DOCKER_DRIVER: overlay2
  KUBERNETES_CPU_LIMIT: 3 # cpu overrides. You can use millicores too, like 1 core and a half would be 1500m
  KUBERNETES_CPU_REQUEST: 2700m # cpu overrides. You can use millicores too, like 1 core and a half would be 1500m
  KUBERNETES_MEMORY_LIMIT: 3Gi # memory overrides
  KUBERNETES_MEMORY_REQUEST: 3Gi # memory overrides

stages:
  - node-modules
  - build

cache:
  paths:
    - node_modules/

node-modules:
  stage: node-modules
  script:
    - npm install

build:
  stage: build
  dependencies:
    - node-modules
  script:
    - make build_ts
