image: node

stages:
  - space
  - node-modules
  - build

cache:
  paths:
  - node_modules/

space:
  stage: space
  script:
    - ls -la /cache
    - df -h
    - ls -la /
    - ls -la /builds

node-modules:
  stage: node-modules
  script:
    - npm install

build:
  stage: build
  dependencies:
    - node-modules
  script:
    - make build_ts
