name: Build

on: push

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache node modules # Caches node_modules folder for subsequent pushes to the same branch
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules- # Take any latest cache if failed to find it for current package-lock.json

      - name: Install Node.js packages
        run: npm ci

      - name: Build ts
        run: make build_ts
